name: MCBattleship
version: '${project.version}'
main: com.fadedbytes.MCBattleship.BattleshipPlugin
api-version: 1.19
description: Play battleship against the computer in Minecraft!
author: PaueteKKUET

commands:
  test:
    description: Test command for debug purposes
    usage: /test
  start:
    description: Start a new game in the current world, if configured
    usage: /start
  setup:
    description: Setup a new game in the current world
    usage: /setup <radarX> <radarY> <radarZ> <canonX> <canonY> <canonZ> <shipboardX> <shipboardY> <shipboardZ>
  leave:
    description: Leave the current game
    usage: /leave